#!/bin/bash -l
#SBATCH -J CombineGVCFs_alldata_X
#SBATCH -o CombineGVCFs_alldata_X.output
#SBATCH -e CombineGVCFs_alldata_X.output
#SBATCH --mail-user gwenna.breton@ebc.uu.se
#SBATCH --mail-type=ALL
#SBATCH -t 65:0:0
#SBATCH -A snic2019-3-12
#SBATCH -p core -n 3

module load bioinfo-tools
module load GATK/3.7
module load tabix/0.2.6

cd /proj/uppstore2017183/b2012165_nobackup/private/Seq_project_cont/Panagiotis_masterproject_mt_X_Y/VariantCalling/Xonly/HC

java -Xmx18g -jar /sw/apps/bioinfo/GATK/3.7/GenomeAnalysisTK.jar -T CombineGVCFs \
-R /proj/uppstore2017183/b2012165_nobackup/private/Seq_project_cont/reference_hg38/GRCh38_full_analysis_set_plus_decoy_hla.fa \
-V 1000GCEU1_HC_AS_X.g.vcf.gz \
-V SAHGPSOT2_HC_AS_X.g.vcf.gz \
-V SGDPJUH1_HC_AS_X.g.vcf.gz \
-V SGDPMBU2_HC_AS_X.g.vcf.gz \
-V 1000GCEU2_HC_AS_X.g.vcf.gz \
-V SAHGPSOT7_HC_AS_X.g.vcf.gz \
-V SGDPJUH2_HC_AS_X.g.vcf.gz \
-V SGDPMBU3_HC_AS_X.g.vcf.gz \
-V SGDPJUH3_HC_AS_X.g.vcf.gz \
-V SGDPMBU4_HC_AS_X.g.vcf.gz \
-V 1000GMEN3_HC_AS_X.g.vcf.gz \
-V SGDPJUH4_HC_AS_X.g.vcf.gz \
-V HGDPDAI5_HC_AS_X.g.vcf.gz \
-V SGDPYOR2_HC_AS_X.g.vcf.gz \
-V HGDPMBU5_HC_AS_X.g.vcf.gz \
-V SGDPFRE1_HC_AS_X.g.vcf.gz \
-V SGDPYOR3_HC_AS_X.g.vcf.gz \
-V HGDPYOR4_HC_AS_X.g.vcf.gz \
-V SGDPMBU1_HC_AS_X.g.vcf.gz \
-V SGDPFRE3_HC_AS_X.g.vcf.gz \
-V SGDPBantuH1_HC_AS_X.g.vcf.gz \
-V SGDPBantuH2_HC_AS_X.g.vcf.gz \
-V SGDPBantuK1_HC_AS_X.g.vcf.gz \
-V SGDPBantuT1_HC_AS_X.g.vcf.gz \
-V SGDPBantuT2_HC_AS_X.g.vcf.gz \
-V SGDPBIA1_HC_AS_X.g.vcf.gz \
-V SGDPBIA2_HC_AS_X.g.vcf.gz \
-V SGDPDIN1_HC_AS_X.g.vcf.gz \
-V SGDPDIN2_HC_AS_X.g.vcf.gz \
-V SGDPDIN3_HC_AS_X.g.vcf.gz \
-V HGDPDIN4_HC_AS_X.g.vcf.gz \
-V SGDPESA1_HC_AS_X.g.vcf.gz \
-V SGDPGAM1_HC_AS_X.g.vcf.gz \
-V SGDPIGB1_HC_AS_X.g.vcf.gz \
-V HGDPJUH5_HC_AS_X.g.vcf.gz \
-V SGDPLEM2_HC_AS_X.g.vcf.gz \
-V SGDPLUH2_HC_AS_X.g.vcf.gz \
-V SGDPLUO1_HC_AS_X.g.vcf.gz \
-V SGDPMAN1_HC_AS_X.g.vcf.gz \
-V SGDPMAN3_HC_AS_X.g.vcf.gz \
-V HGDPMAN4_HC_AS_X.g.vcf.gz \
-V SGDPMAS1_HC_AS_X.g.vcf.gz \
-V SGDPMAS2_HC_AS_X.g.vcf.gz \
-V SGDPMEN1_HC_AS_X.g.vcf.gz \
-V SGDPMOZ1_HC_AS_X.g.vcf.gz \
-V SGDPSAH1_HC_AS_X.g.vcf.gz \
-V SGDPSAH2_HC_AS_X.g.vcf.gz \
-V SGDPDai1_HC_AS_X.g.vcf.gz \
-V SGDPDai2_HC_AS_X.g.vcf.gz \
-V SGDPDai3_HC_AS_X.g.vcf.gz \
-V SGDPDai4_HC_AS_X.g.vcf.gz \
-V SGDPKAR1_HC_AS_X.g.vcf.gz \
-V SGDPKAR3_HC_AS_X.g.vcf.gz \
-V HGDPKAR5_HC_AS_X.g.vcf.gz \
-V SGDPPAP6_HC_AS_X.g.vcf.gz \
-V SGDPPAP10_HC_AS_X.g.vcf.gz \
-V SGDPPAP12_HC_AS_X.g.vcf.gz \
-V HGDPPAPe_HC_AS_X.g.vcf.gz \
-V HGDPFRE4_HC_AS_X.g.vcf.gz \
-V SAHGPCOL1_HC_AS_X.g.vcf.gz \
-V SAHGPCOL2_HC_AS_X.g.vcf.gz \
-V SAHGPCOL3_HC_AS_X.g.vcf.gz \
-V SAHGPCOL4_HC_AS_X.g.vcf.gz \
-V SAHGPCOL5_HC_AS_X.g.vcf.gz \
-V SAHGPCOL6_HC_AS_X.g.vcf.gz \
-V SAHGPCOL7_HC_AS_X.g.vcf.gz \
-V SAHGPCOL8_HC_AS_X.g.vcf.gz \
-V SAHGPZUL1_HC_AS_X.g.vcf.gz \
-V SAHGPSOT1_HC_AS_X.g.vcf.gz \
-V SAHGPSOT3_HC_AS_X.g.vcf.gz \
-V SAHGPSOT4_HC_AS_X.g.vcf.gz \
-V SAHGPSOT5_HC_AS_X.g.vcf.gz \
-V SAHGPSOT6_HC_AS_X.g.vcf.gz \
-V SAHGPXHO1_HC_AS_X.g.vcf.gz \
-V SAHGPXHO2_HC_AS_X.g.vcf.gz \
-V SAHGPXHO3_HC_AS_X.g.vcf.gz \
-V SAHGPXHO4_HC_AS_X.g.vcf.gz \
-V SAHGPXHO5_HC_AS_X.g.vcf.gz \
-V SAHGPXHO6_HC_AS_X.g.vcf.gz \
-V SAHGPXHO7_HC_AS_X.g.vcf.gz \
-V SAHGPXHO8_HC_AS_X.g.vcf.gz \
-V SGDPBantuK2_HC_AS_X.g.vcf.gz \
-V SGDPESA2_HC_AS_X.g.vcf.gz \
-V 1000GESA3_HC_AS_X.g.vcf.gz \
-V SGDPGAM2_HC_AS_X.g.vcf.gz \
-V SGDPIGB2_HC_AS_X.g.vcf.gz \
-V SGDPKHO1_HC_AS_X.g.vcf.gz \
-V SGDPKHO2_HC_AS_X.g.vcf.gz \
-V SGDPKON2_HC_AS_X.g.vcf.gz \
-V SGDPLEM1_HC_AS_X.g.vcf.gz \
-V SGDPLUH1_HC_AS_X.g.vcf.gz \
-V 1000GLUH3_HC_AS_X.g.vcf.gz \
-V SGDPLUO2_HC_AS_X.g.vcf.gz \
-V SGDPMAN2_HC_AS_X.g.vcf.gz \
-V 1000GMAN5_HC_AS_X.g.vcf.gz \
-V SGDPMEN2_HC_AS_X.g.vcf.gz \
-V SGDPMOZ2_HC_AS_X.g.vcf.gz \
-V SGDPSOM1_HC_AS_X.g.vcf.gz \
-V SGDPYOR1_HC_AS_X.g.vcf.gz \
-V 1000GDAI6_HC_AS_X.g.vcf.gz \
-V SGDPKAR2_HC_AS_X.g.vcf.gz \
-V KAR4_HC_AS_X.g.vcf.gz \
-V SGDPPAP1_HC_AS_X.g.vcf.gz \
-V SGDPPAP13_HC_AS_X.g.vcf.gz \
-V SGDPFRE2_HC_AS_X.g.vcf.gz \
-V PNP001_merge_HC_AS_X.g.vcf.gz \
-V PNP002_merge_HC_AS_X.g.vcf.gz \
-V PNP006_merge_HC_AS_X.g.vcf.gz \
-V PNP010_merge_HC_AS_X.g.vcf.gz \
-V PNP011_merge_HC_AS_X.g.vcf.gz \
-V PNP012_merge_HC_AS_X.g.vcf.gz \
-V PNP013_merge_HC_AS_X.g.vcf.gz \
-V PNP014_merge_HC_AS_X.g.vcf.gz \
-V PNP020_merge_HC_AS_X.g.vcf.gz \
-V PNP021_merge_HC_AS_X.g.vcf.gz \
-V PNP022_merge_HC_AS_X.g.vcf.gz \
-V PNP023_merge_HC_AS_X.g.vcf.gz \
-V PNP030_merge_HC_AS_X.g.vcf.gz \
-V PNP031_merge_HC_AS_X.g.vcf.gz \
-V PNP032_merge_HC_AS_X.g.vcf.gz \
-V PNP033_merge_HC_AS_X.g.vcf.gz \
-V PNP040_merge_HC_AS_X.g.vcf.gz \
-V PNP041_merge_HC_AS_X.g.vcf.gz \
-V PNP043_merge_HC_AS_X.g.vcf.gz \
-V PNP044_merge_HC_AS_X.g.vcf.gz \
-V PNP050_merge_HC_AS_X.g.vcf.gz \
-V PNP051_merge_HC_AS_X.g.vcf.gz \
-V PNP053_merge_HC_AS_X.g.vcf.gz \
-V PNP066_merge_HC_AS_X.g.vcf.gz \
-V PNP070_merge_HC_AS_X.g.vcf.gz \
-V PNP074_merge_HC_AS_X.g.vcf.gz \
-V PNP080_merge_HC_AS_X.g.vcf.gz \
-V PNP083_merge_HC_AS_X.g.vcf.gz \
-V PNP084_merge_HC_AS_X.g.vcf.gz \
-V KSP063_merge_HC_AS_X.g.vcf.gz \
-V KSP067_merge_HC_AS_X.g.vcf.gz \
-V KSP069_merge_HC_AS_X.g.vcf.gz \
-V KSP092_merge_HC_AS_X.g.vcf.gz \
-V KSP096_merge_HC_AS_X.g.vcf.gz \
-V KSP103_merge_HC_AS_X.g.vcf.gz \
-V KSP105_merge_HC_AS_X.g.vcf.gz \
-V KSP106_merge_HC_AS_X.g.vcf.gz \
-V KSP111_merge_HC_AS_X.g.vcf.gz \
-V KSP116_merge_HC_AS_X.g.vcf.gz \
-V KSP124_merge_HC_AS_X.g.vcf.gz \
-V KSP137_merge_HC_AS_X.g.vcf.gz \
-V KSP139_merge_HC_AS_X.g.vcf.gz \
-V KSP140_merge_HC_AS_X.g.vcf.gz \
-V KSP146_merge_HC_AS_X.g.vcf.gz \
-V KSP150_merge_HC_AS_X.g.vcf.gz \
-V KSP152_merge_HC_AS_X.g.vcf.gz \
-V KSP154_merge_HC_AS_X.g.vcf.gz \
-V KSP155_merge_HC_AS_X.g.vcf.gz \
-V PNP000_HC_AS_X.g.vcf.gz \
-V PNP003_HC_AS_X.g.vcf.gz \
-V PNP004_HC_AS_X.g.vcf.gz \
-V PNP005_HC_AS_X.g.vcf.gz \
-V PNP024_HC_AS_X.g.vcf.gz \
-V PNP034_HC_AS_X.g.vcf.gz \
-V PNP042_HC_AS_X.g.vcf.gz \
-V PNP052_HC_AS_X.g.vcf.gz \
-V PNP054_HC_AS_X.g.vcf.gz \
-V PNP060_HC_AS_X.g.vcf.gz \
-V PNP061_HC_AS_X.g.vcf.gz \
-V PNP062_HC_AS_X.g.vcf.gz \
-V PNP063_HC_AS_X.g.vcf.gz \
-V PNP064_HC_AS_X.g.vcf.gz \
-V PNP065_HC_AS_X.g.vcf.gz \
-V PNP071_HC_AS_X.g.vcf.gz \
-V PNP072_HC_AS_X.g.vcf.gz \
-V PNP073_HC_AS_X.g.vcf.gz \
-V PNP081_HC_AS_X.g.vcf.gz \
-V PNP082_HC_AS_X.g.vcf.gz \
-V KSP062_HC_AS_X.g.vcf.gz \
-V KSP065_HC_AS_X.g.vcf.gz \
-V KSP224_HC_AS_X.g.vcf.gz \
-V KSP225_HC_AS_X.g.vcf.gz \
-V KSP228_HC_AS_X.g.vcf.gz \
-V KSP134_HC_AS_X.g.vcf.gz \
-G Standard -G AS_Standard \
-o /proj/uppstore2017183/b2012165_nobackup/private/Seq_project_cont/Gwenna_Xchr/VariantCalling/alldatacomb.X.20190808.179ind.g.vcf.gz




